# Site settings
title: Amy Groshek
description: Freelance Web development, Moodle and SCORM consulting, editing, and writing
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Amy Groshek
user_description: Hi. I'm a freelance web developer, writer, and editor. I'm also a PhD student in English Literature at the University of Wisconsin Madison. I have 10 years of experience in the online learning industry, working mostly with the Moodle LMS.
user_title: Web Developer, Writer, Editor, Consultant
email: amygroshek@gmail.com
twitter_username: amygroshek
github_username:  amygroshek
# gplus_username:  lorem_ipsum
linkedin_username:  amy-groshek-b7a2683

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']

sass:
    sass_dir: _sass
